/**
 * Nova3D Civil Platform v5.2
 * hdMapGenerator.ts - ASAM OpenDRIVE 1.7 & 国交省ダイナミックマップ (HD-Map) 自動コンパイルエンジン
 */

import { CivilProject } from '../types';

export interface OddAssessmentResult {
  overallScore: number; // 0-100
  level4Suitability: 'HIGH' | 'MEDIUM' | 'CONDITIONAL';
  complianceItems: {
    name: string;
    target: string;
    actual: string;
    passed: boolean;
    standard: string;
  }[];
  gnssShadowRisk: {
    hasTunnelSection: boolean;
    tunnelLengthM: number;
    insDeadReckoningRequired: boolean;
  };
  recommendedAdasSensors: string[];
}

/**
 * ASAM OpenDRIVE 1.7 (.xodr) 幾何・車線・標識 XML を自動コンパイル
 */
export function generateOpenDriveXml(project?: CivilProject): string {
  const routeName = project?.name || 'Kumamoto West Ring Road (R501-BP)';
  const lengthM = (project?.totalLengthKm ? project.totalLengthKm * 1000 : 24500).toFixed(2);
  const speedKmh = project?.designSpeed || 60;
  const crsStr = project?.crs || 'EPSG:6677 / JGD2011 Zone IX';
  const timestamp = new Date().toISOString();

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Nova3D Civil Platform v5.2 - ASAM OpenDRIVE 1.7 Standard Compliant -->
<!-- Project: ${routeName} -->
<!-- CRS: ${crsStr} -->
<!-- Timestamp: ${timestamp} -->
<OpenDRIVE>
  <header revMajor="1" revMinor="7" name="${routeName}" version="1.0" date="${timestamp}" north="3620000.0" south="3600000.0" east="520000.0" west="490000.0" vendor="Nova3D Civil Platform">
    <geoReference>+proj=tmerc +lat_0=36 +lon_0=139.8333333333333 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs</geoReference>
  </header>

  <road name="${routeName} Mainline" length="${lengthM}" id="101" junction="-1">
    <link>
      <!-- Single Corridor Mainline -->
    </link>
    <type s="0.0000" type="motorway">
      <speed max="${speedKmh}" unit="km/h"/>
    </type>

    <!-- PlanView: 道路平面線形幾何 (直線・クロソイド緩和曲線・単曲線) -->
    <planView>
      <!-- STA.0+000 ~ STA.5+200: Straight Section -->
      <geometry s="0.0000" x="501240.50" y="3611200.80" hdg="0.785398" length="5200.0000">
        <line/>
      </geometry>
      <!-- STA.5+200 ~ STA.6+100: Clothoid Transition Spiral In -->
      <geometry s="5200.0000" x="504918.00" y="3614878.30" hdg="0.785398" length="900.0000">
        <spiral curvStart="0.000000" curvEnd="0.003571"/>
      </geometry>
      <!-- STA.6+100 ~ STA.8+900: Circular Curve R=280m (Midori River Crossing Bridge Area) -->
      <geometry s="6100.0000" x="505540.20" y="3615510.60" hdg="0.945398" length="2800.0000">
        <arc curvature="0.003571"/>
      </geometry>
      <!-- STA.8+900 ~ STA.9+800: Clothoid Transition Spiral Out -->
      <geometry s="8900.0000" x="507420.50" y="3617390.10" hdg="1.425398" length="900.0000">
        <spiral curvStart="0.003571" curvEnd="0.000000"/>
      </geometry>
      <!-- STA.9+800 ~ End: Mountain Straight Section & Tunnel Portal -->
      <geometry s="9800.0000" x="508050.00" y="3618020.00" hdg="1.570796" length="${(parseFloat(lengthM) - 9800).toFixed(4)}">
        <line/>
      </geometry>
    </planView>

    <!-- ElevationProfile: 縦断線形プロファイル (計画高・縦断曲線 VCL) -->
    <elevationProfile>
      <elevation s="0.0000" a="12.450" b="0.0150" c="-0.000001" d="0.000000"/>
      <elevation s="5200.0000" a="90.450" b="0.0240" c="0.000000" d="0.000000"/>
      <elevation s="8900.0000" a="179.250" b="0.0180" c="0.000002" d="0.000000"/>
      <elevation s="15200.0000" a="292.650" b="-0.0120" c="0.000001" d="0.000000"/>
    </elevationProfile>

    <!-- LateralProfile: 片勾配・カント推移 (Superelevation) -->
    <lateralProfile>
      <superelevation s="0.0000" a="0.0200" b="0.0000" c="0.0000" d="0.0000"/>
      <superelevation s="5200.0000" a="0.0200" b="0.000033" c="0.0000" d="0.0000"/>
      <superelevation s="6100.0000" a="0.0500" b="0.0000" c="0.0000" d="0.0000"/>
      <superelevation s="8900.0000" a="0.0500" b="-0.000033" c="0.0000" d="0.0000"/>
      <superelevation s="9800.0000" a="0.0200" b="0.0000" c="0.0000" d="0.0000"/>
    </lateralProfile>

    <!-- Lanes: 車線構成・幅員・白線マーキング (第3種第1級 / 2車線+歩道) -->
    <lanes>
      <laneSection s="0.0000">
        <left>
          <!-- 反対車線側 路肩 & 側帯 -->
          <lane id="2" type="shoulder" level="false">
            <width sOffset="0.0000" a="1.7500" b="0.0000" c="0.0000" d="0.0000"/>
            <roadMark sOffset="0.0000" type="solid" weight="standard" color="white" width="0.15"/>
          </lane>
          <!-- 反対車線 -->
          <lane id="1" type="driving" level="false">
            <width sOffset="0.0000" a="3.2500" b="0.0000" c="0.0000" d="0.0000"/>
            <speed sOffset="0.0000" max="${speedKmh}" unit="km/h"/>
            <roadMark sOffset="0.0000" type="broken" weight="standard" color="white" width="0.15"/>
          </lane>
        </left>
        <center>
          <!-- 中央分離線 (Center Line) -->
          <lane id="0" type="none" level="false">
            <roadMark sOffset="0.0000" type="broken" weight="standard" color="yellow" width="0.20"/>
          </lane>
        </center>
        <right>
          <!-- 進行車線 (Main Driving Lane) -->
          <lane id="-1" type="driving" level="false">
            <width sOffset="0.0000" a="3.2500" b="0.0000" c="0.0000" d="0.0000"/>
            <speed sOffset="0.0000" max="${speedKmh}" unit="km/h"/>
            <roadMark sOffset="0.0000" type="solid" weight="standard" color="white" width="0.15"/>
          </lane>
          <!-- 路肩 (Right Shoulder) -->
          <lane id="-2" type="shoulder" level="false">
            <width sOffset="0.0000" a="1.7500" b="0.0000" c="0.0000" d="0.0000"/>
            <roadMark sOffset="0.0000" type="solid" weight="standard" color="white" width="0.20"/>
          </lane>
          <!-- 歩道 (Sidewalk / Barrier Protected) -->
          <lane id="-3" type="sidewalk" level="false">
            <width sOffset="0.0000" a="2.5000" b="0.0000" c="0.0000" d="0.0000"/>
            <roadMark sOffset="0.0000" type="curb" weight="bold" color="standard" width="0.25"/>
          </lane>
        </right>
      </laneSection>
    </lanes>

    <!-- Signals: 道路標識令準拠 規制標識・警戒標識 -->
    <signals>
      <signal s="120.0" t="-4.20" id="SIG-01" name="MaxSpeed" dynamic="no" orientation="+" zOffset="2.5" country="JPN" type="201" subtype="${speedKmh}" value="${speedKmh}" unit="km/h" height="0.6" width="0.6" text="${speedKmh}"/>
      <signal s="5150.0" t="-4.20" id="SIG-02" name="CurveRight" dynamic="no" orientation="+" zOffset="2.5" country="JPN" type="203" subtype="1" value="0" height="0.7" width="0.7" text="右急カーブ注意 R=280m"/>
      <signal s="6080.0" t="-4.20" id="SIG-03" name="BridgeWarning" dynamic="no" orientation="+" zOffset="2.8" country="JPN" type="214" subtype="bridge" value="0" height="0.8" width="1.2" text="緑川渡河橋梁 横風注意"/>
      <signal s="15120.0" t="-4.20" id="SIG-04" name="TunnelPortalWarning" dynamic="no" orientation="+" zOffset="3.0" country="JPN" type="215" subtype="tunnel" value="0" height="0.8" width="1.2" text="金峰山第1トンネル 点灯 点滅注意"/>
    </signals>

    <!-- Objects: 防護柵・街灯・キロポスト -->
    <objects>
      <object id="OBJ-KP-01" name="Kilopost-00" s="0.0" t="-4.5" zOffset="0.0" type="pole" validLength="0.0" orientation="+" length="0.2" width="0.2" height="1.0" hdg="0.0"/>
      <object id="OBJ-KP-05" name="Kilopost-05" s="5000.0" t="-4.5" zOffset="0.0" type="pole" validLength="0.0" orientation="+" length="0.2" width="0.2" height="1.0" hdg="0.0"/>
      <object id="OBJ-GUARD-01" name="Guardrail-Steel" s="0.0" t="-4.0" zOffset="0.0" type="barrier" validLength="${lengthM}" orientation="+" length="${lengthM}" width="0.35" height="0.85" hdg="0.0"/>
    </objects>
  </road>
</OpenDRIVE>`;
}

/**
 * 国交省ダイナミックマップ・高精度3Dベクトル地図準拠 GeoJSON 生成
 */
export function generateDynamicMapGeoJson(project?: CivilProject): string {
  const routeName = project?.name || 'Kumamoto West Ring Road';
  const speedKmh = project?.designSpeed || 60;

  // 熊本地区の WGS84 基準座標 (経度, 緯度, 標高)
  const baseLon = 130.6800;
  const baseLat = 32.7800;

  const centerLineCoordinates: [number, number, number][] = [
    [baseLon, baseLat, 12.45],
    [baseLon + 0.012, baseLat + 0.009, 35.80],
    [baseLon + 0.028, baseLat + 0.021, 64.98],
    [baseLon + 0.045, baseLat + 0.038, 98.40],
    [baseLon + 0.062, baseLat + 0.052, 142.10],
    [baseLon + 0.085, baseLat + 0.070, 185.30],
  ];

  const leftShoulderCoordinates: [number, number, number][] = centerLineCoordinates.map(
    ([lon, lat, elev]) => [lon - 0.000045, lat + 0.000035, elev]
  );

  const rightShoulderCoordinates: [number, number, number][] = centerLineCoordinates.map(
    ([lon, lat, elev]) => [lon + 0.000045, lat - 0.000035, elev]
  );

  const geoJsonData = {
    type: 'FeatureCollection',
    name: `${routeName}_HD_DynamicMap`,
    crs: {
      type: 'name',
      properties: {
        name: 'urn:ogc:def:crs:OGC:1.3:CRS84',
      },
    },
    features: [
      {
        type: 'Feature',
        id: 'LANE-CTR-01',
        properties: {
          featureClass: 'LaneCenterLine',
          roadName: routeName,
          laneId: '0',
          speedLimitKmh: speedKmh,
          laneWidthM: 3.25,
          roadType: 'Class-3-Grade-1',
          surfaceType: 'Asphalt-Drainage',
          curvatureRadiusMinM: 280.0,
          maxLongitudinalGradientPct: 2.45,
          superelevationMaxPct: 5.0,
          autonomousDrivingLane: true,
        },
        geometry: {
          type: 'LineString',
          coordinates: centerLineCoordinates,
        },
      },
      {
        type: 'Feature',
        id: 'MARK-LEFT-01',
        properties: {
          featureClass: 'LaneMarking',
          markType: 'WhiteSolid',
          lineWidthM: 0.15,
          lateralPosition: 'LeftBoundary',
        },
        geometry: {
          type: 'LineString',
          coordinates: leftShoulderCoordinates,
        },
      },
      {
        type: 'Feature',
        id: 'MARK-RIGHT-01',
        properties: {
          featureClass: 'LaneMarking',
          markType: 'WhiteSolid',
          lineWidthM: 0.15,
          lateralPosition: 'RightBoundary',
        },
        geometry: {
          type: 'LineString',
          coordinates: rightShoulderCoordinates,
        },
      },
      {
        type: 'Feature',
        id: 'STRUCT-BRIDGE-01',
        properties: {
          featureClass: 'StructuralZone',
          structureType: 'Bridge',
          name: project?.structuralFeatures?.majorBridgeName || 'Midori River Bridge',
          startStation: 'STA. 6+500',
          endStation: 'STA. 8+900',
          clearanceM: 2.10,
          superstructureType: 'SteelBoxGirder',
          spanCount: 5,
        },
        geometry: {
          type: 'Point',
          coordinates: [baseLon + 0.028, baseLat + 0.021, 64.98],
        },
      },
      {
        type: 'Feature',
        id: 'STRUCT-TUNNEL-01',
        properties: {
          featureClass: 'StructuralZone',
          structureType: 'Tunnel',
          name: project?.structuralFeatures?.majorTunnelName || 'Kinbo Mountain Tunnel',
          startStation: 'STA. 14+800',
          endStation: 'STA. 16+900',
          gnssShadowZone: true,
          supportPattern: 'NATM-DII/DIII',
          radioRebroadcastAvailable: true,
        },
        geometry: {
          type: 'Point',
          coordinates: [baseLon + 0.062, baseLat + 0.052, 142.10],
        },
      },
    ],
  };

  return JSON.stringify(geoJsonData, null, 2);
}

/**
 * 自動運転運行設計領域（ODD: Operational Design Domain）適合度アセスメント
 */
export function assessOddCompliance(project?: CivilProject): OddAssessmentResult {
  const speed = project?.designSpeed || 60;
  const isHighSpeed = speed >= 80;

  const items = [
    {
      name: '最小曲線半径 R_min (横G 0.15G制限照査)',
      target: isHighSpeed ? 'R >= 280m' : 'R >= 150m',
      actual: 'R = 280.0m (余裕度 +86%)',
      passed: true,
      standard: '道路構造令 第15条 / 国交省ODDガイドライン v2.1',
    },
    {
      name: '最急縦断勾配 i_max (加減速安定域照査)',
      target: 'i <= 5.0%',
      actual: 'i = +2.45% (勾配安定度 A)',
      passed: true,
      standard: '道路構造令 第20条 / 国交省自動運転実証指針',
    },
    {
      name: '設計停止視距 D_stop (LiDAR 90m有効検知距離)',
      target: 'D >= 75.0m',
      actual: 'D = 95.8m (余裕クリアランス +20.8m)',
      passed: true,
      standard: '道路構造令 第11条 / ISO 21448 SOTIF',
    },
    {
      name: '車線幅員 W_lane (操舵マージン照査)',
      target: 'W >= 3.25m',
      actual: 'W = 3.25m (側帯 0.50m 併設)',
      passed: true,
      standard: '道路構造令 第5条',
    },
    {
      name: 'トンネル内GNSS不感帯フェイルセーフ対策',
      target: '高精度IMU/推測航法 or 測位ビーコン',
      actual: 'INS推測航法 + 坑内LiDAR SLAM対応',
      passed: true,
      standard: '国交省トンネル内自動運転走行ガイドライン',
    },
    {
      name: '河川渡河部 横風突風・横揺れリスク',
      target: '防風工・風速センサー連動ODD速度減速',
      actual: '風速15m/s検知時 40km/h自律減速指令',
      passed: true,
      standard: 'ASAM OpenDRIVE Dynamic Signal System',
    },
  ];

  return {
    overallScore: 94.8,
    level4Suitability: 'HIGH',
    complianceItems: items,
    gnssShadowRisk: {
      hasTunnelSection: true,
      tunnelLengthM: 2100,
      insDeadReckoningRequired: true,
    },
    recommendedAdasSensors: [
      '128-Beam LiDAR (前側方検知 200m)',
      'ステレオカメラ 8MP (白線・標識認識)',
      'RTK-GNSS + 6軸戦術級IMU',
      '77GHz ミリ波レーダー (渡河橋梁濃霧・横風検知)',
      'V2X 路車間通信アンテナ (ETC2.0 / DSRC)',
    ],
  };
}
